SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MetricSetGroups](
	[MetricSetName_StartWith] [varchar](50) NOT NULL,
	[GroupName] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MetricSetName_StartWith] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
